sudo: required
dist: xenial

env:
  - IMAGE=ubuntu-daily:bionic SCRIPT="make lint"
  - IMAGE=ubuntu-daily:bionic SCRIPT=./scripts/runtests.sh
  - IMAGE=ubuntu-daily:focal SCRIPT=./scripts/runtests.sh
  - IMAGE=ubuntu-daily:groovy SCRIPT=./scripts/runtests.sh

language: bash

script:
  - sudo ./scripts/test-in-lxd.sh "$IMAGE" "$SCRIPT"
