name: TICS

on:
  workflow_dispatch:
  schedule:
    - cron: '17 5 * * 6'  # Run at 5:17a (arbitrary) on Saturday
  push:
    paths:
      - '.github/workflows/tics.yaml'
  pull_request:
    paths:
      - '.github/workflows/tics.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TICS:
    runs-on: [self-hosted, linux, amd64, tiobe, noble]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          sudo ./scripts/installdeps.sh

      - name: Coverage
        run: |
          make coverage

      - name: Detach TICS if needed
        env:
          TICSAUTHTOKEN: ${{ secrets.TICSAUTHTOKEN }}
        run: |
          source ~/.profile
          TICSMaintenance -project subiquity -detach

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: subiquity
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
